- membuat index php
- membuat home php //edit fitur1
- membuat profil php //edit fitur1
- membuat kontak php //edit fitur1

- membuat hyperlink php //edit fitur2
- membuat img src //edit fitur2
- membuat form login ////edit fitur2
- depo
- wede
- fm
